spring.application.name=Cofrin API

# Conexão com o banco 
spring.datasource.url=jdbc:postgresql://localhost:5432/cofrin
spring.datasource.username=cofrin
spring.datasource.password=cofrin

# Comportamento do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
